name: Build Verification of Maven project

on:
  workflow_call:
    secrets:
      GPG_PRIVATE_KEY:
        required: true
      GPG_PRIVATE_KEY_PASSPHRASE:
        required: true
      SCM_USER:
        required: true
      SCM_TOKEN:
        required: true

permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  packages: read
  pull-requests: read

env:
  JAVA_VERSION: 21
  MAVEN_CLI_OPTS: |
    --batch-mode \
    --settings /tmp/java_maven_settings.xml \
    -DaltDeploymentRepository=github::https://maven.pkg.github.com/${GITHUB_REPOSITORY}/ \
    -DconnectionUrl=github::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} \
    -DdeveloperConnectionUrl=github::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git

jobs:
  call-workflow-build:
    uses: PallasSystems/infrastructure-ci/.github/workflows/java_maven_build.yml@main
    secrets: inherit
  call-workflow-integration-tests:
    uses: PallasSystems/infrastructure-ci/.github/workflows/java_maven_unit_test.yml@main
    secrets: inherit
  call-workflow-unit-tests:
    uses: PallasSystems/infrastructure-ci/.github/workflows/java_maven_unit_test.yml@main
    secrets: inherit
