name: "Integration Test and Coverage Results"

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'The Version of Java to use when compiling'
        default: '21'
        required: false
        type: string
      JACOCO_VERSION:
        description: 'The Version of Jacoco Maven plugin to run for code coverage'
        default: '0.8.12'
        required: false
        type: string
      MAVEN_ARGS:
        description: 'The Maven CLI options to use in the build command'
        default: --batch-mode --show-version --settings /tmp/java_maven_settings.xml
        required: false
        type: string
      MAVEN_OPTS:
          description: 'The build specific Maven CLI options to use in the build command'
          default: -Ddocker.skip=true -Dgpg.skip=true
          required: false
          type: string
    secrets:
      SCM_USER:
        required: true
      SCM_TOKEN:
        required: true

permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  packages: read
  pull-requests: read

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4.2.2
      
      - name: Set up JDK ${{ inputs.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          cache: "maven"
          distribution: "temurin"
          java-version: ${{ inputs.JAVA_VERSION }}

      - name: Retrieve Maven Settings File
        run: wget https://raw.githubusercontent.com/PallasSystems/infrastructure-ci/main/.github/workflows/java_maven_settings.xml -P /tmp/

      - name: Jacoco Coverage
        run: mvn org.jacoco:jacoco-maven-plugin:${{ inputs.JACOCO_VERSION }}:prepare-agent-integration integration-test org.jacoco:jacoco-maven-plugin:${{ inputs.JACOCO_VERSION }}:report-integration
        env:
          GITHUB_USER: ${{ secrets.SCM_USER }}
          GITHUB_TOKEN: ${{ secrets.SCM_TOKEN }}
          MAVEN_ARGS: ${{ inputs.MAVEN_ARGS }}
          MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }}  

      - name: Add Jacoco Coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/**/target/**/jacoco.xml
          token: ${{ secrets.SCM_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

      - name: Upload Jacoco Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: integration-coverage-report-markdown
          path: ${{ github.workspace }}/**/target/**/jacoco.xml
          retention-days: 30