name: "Unit Test and Coverage Results"

on:
  workflow_call:
    secrets:
      SCM_USER:
        required: true
      SCM_TOKEN:
        required: true

permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  packages: read
  pull-requests: read

env:
  JAVA_VERSION: 21
  MAVEN_CLI_OPTS: |-
    --batch-mode 
    --settings /tmp/java_maven_settings.xml
    -Ddocker.skip=true
    -Dgpg.skip=true
  JACOCO_VERSION: "0.8.12"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4.2.2
      
      - name: Set up JDK ${env.JAVA_VERSION}
        uses: actions/setup-java@v4
        with:
          cache: "maven"
          distribution: "temurin"
          java-version: ${env.JAVA_VERSION}

      - name: Retrieve Maven Settings File
        run: wget https://raw.githubusercontent.com/PallasSystems/infrastructure-ci/main/.github/workflows/java_maven_settings.xml -P /tmp/

      - name: Jacoco Coverage
        run: mvn org.jacoco:jacoco-maven-plugin:$JACOCO_VERSION:prepare-agent test org.jacoco:jacoco-maven-plugin:$JACOCO_VERSION:report
        env:
          GITHUB_USER: ${{ secrets.SCM_USER }}
          GITHUB_TOKEN: ${{ secrets.SCM_TOKEN }}

      - name: Add Jacoco Coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/**/target/**/jacoco.xml
          token: ${{ secrets.SCM_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

      - name: Upload Jacoco Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-markdown
          path: ${{ github.workspace }}/**/target/**/jacoco.xml
          retention-days: 30