name: Build Verification of Maven project

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'The Version of Java to use when compiling'
        default: '21'
        required: false
        type: string
      JACOCO_VERSION:
        description: 'The Version of Jacoco Maven plugin to run for code coverage'
        default: '0.8.12'
        required: false
        type: string
      MAVEN_ARGS:
        description: 'The Maven CLI options to use in the build command'
        default: --batch-mode --show-version --settings /tmp/java_maven_settings.xml
        required: false
        type: string
      MAVEN_BUILD_OPTS:
        description: 'The build specific Maven CLI options to use in the build command'
        default: -Ddocker.skip=true -Dgpg.skip=true -DskipTests=true
        required: false
        type: string
      MAVEN_IT_OPTS:
        description: 'The build specific Maven CLI options to use in the build command'
        default: -Ddocker.skip=true -Dgpg.skip=true
        required: false
        type: string
      MAVEN_TEST_OPTS:
        description: 'The build specific Maven CLI options to use in the build command'
        default: -DskipITs=true -Ddocker.skip=true -Dgpg.skip=true
        required: false
        type: string
    secrets:
      GPG_PRIVATE_KEY:
        required: true
      GPG_PRIVATE_KEY_PASSPHRASE:
        required: true
      SCM_USER:
        required: true
      SCM_TOKEN:
        required: true

permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  packages: read
  pull-requests: read

jobs:
  call-workflow-build:
    uses: PallasSystems/infrastructure-ci/.github/workflows/java_maven_build.yml@main
    secrets: inherit
    with:
      JAVA_VERSION: ${{ inputs.JAVA_VERSION }}
      MAVEN_ARGS: ${{ inputs.MAVEN_ARGS }}
      MAVEN_OPTS: ${{ inputs.MAVEN_BUILD_OPTS }}
  
  call-workflow-integration-tests:
    uses: PallasSystems/infrastructure-ci/.github/workflows/java_maven_integration_test.yml@main
    secrets: inherit
    with:
      JAVA_VERSION: ${{ inputs.JAVA_VERSION }}
      JACOCO_VERSION: ${{ inputs.JACOCO_VERSION }}
      MAVEN_ARGS: ${{ inputs.MAVEN_ARGS }}
      MAVEN_OPTS: ${{ inputs.MAVEN_IT_OPTS }}

  call-workflow-unit-tests:
    uses: PallasSystems/infrastructure-ci/.github/workflows/java_maven_unit_test.yml@main
    secrets: inherit
    with:
      JAVA_VERSION: ${{ inputs.JAVA_VERSION }}
      JACOCO_VERSION: ${{ inputs.JACOCO_VERSION }}
      MAVEN_ARGS: ${{ inputs.MAVEN_ARGS }}
      MAVEN_OPTS: ${{ inputs.MAVEN_TEST_OPTS }}
