name: Build Verification of Maven project

on:
  workflow_call:
    secrets:
      GPG_PRIVATE_KEY:
        required: true
      GPG_PRIVATE_KEY_PASSPHRASE:
        required: true
      SCM_USER:
        required: true
      SCM_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  packages: read
  pull-requests: read

jobs:
  call-workflow-build:
    uses: PallasSystems/infrastructure-ci/.github/workflows/java_maven_build.yml@main
    secrets: inherit
  call-workflow-unit-test:
    uses: PallasSystems/infrastructure-ci/.github/workflows/java_maven_unit_test.yml@main
    secrets: inherit
