name: Build of Maven project

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'The Version of Java to use when compiling'
        default: '21'
        required: false
        type: string
      MAVEN_CLI_OPTS:
        description: 'The Maven CLI options to use in the build command'
        default: |-
          --batch-mode \
          --show-version \
          --settings /tmp/java_maven_settings.xml
        required: false
        type: string
      MAVEN_BUILD_CLI_OPTS:
          description: 'The build specific Maven CLI options to use in the build command'
          default: |-
            -Ddocker.skip=true \
            -Dgpg.skip=true \
            -DskipTests=true
          required: false
          type: string
    secrets:
      SCM_USER:
        required: true
      SCM_TOKEN:
        required: true

permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  packages: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK ${{ inputs.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          cache: "maven"
          distribution: "temurin"
          java-version: ${{ inputs.JAVA_VERSION }}

      - name: Retrieve Maven Settings File
        run: wget https://raw.githubusercontent.com/PallasSystems/infrastructure-ci/main/.github/workflows/java_maven_settings.xml -P /tmp/

      - name: Build with Maven
        run: mvn clean install ${{ inputs.MAVEN_BUILD_CLI_OPTS }}
        env:
          GITHUB_USER: ${{ secrets.SCM_USER }}
          GITHUB_TOKEN: ${{ secrets.SCM_TOKEN }}
          MAVEN_CLI_OPTS: ${{ inputs.MAVEN_CLI_OPTS }}