name: "PMD & CPD SAST"

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'The Version of Java to use when compiling'
        default: '21'
        required: false
        type: string
      PMD_VERSION:
        description: 'The Version of Maven PMD plugin to run for SAST'
        default: '3.26.0'
        required: false
        type: string
      MAVEN_ARGS:
        description: 'The Maven CLI options to use in the build command'
        default: --batch-mode --show-version --settings /tmp/java_maven_settings.xml
        required: false
        type: string
      MAVEN_OPTS:
        description: 'The build specific Maven CLI options to use in the build command'
        default: -Dformat=txt -DminimumPriority=100 -Ddocker.skip=true -Dgpg.skip=true
        required: false
        type: string
    secrets:
      SCM_USER:
        required: true
      SCM_TOKEN:
        required: true

permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  packages: read
  pull-requests: write

jobs:
  pmd-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.SCM_TOKEN }}
      
      - name: Set up JDK ${{ inputs.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          cache: "maven"
          distribution: "temurin"
          java-version: ${{ inputs.JAVA_VERSION }}

      - name: Retrieve Maven Settings File
        run: wget https://raw.githubusercontent.com/PallasSystems/infrastructure-ci/main/.github/workflows/java_maven_settings.xml -P /tmp/

      - name: Run PMD
        run: mvn org.apache.maven.plugins:maven-pmd-plugin:${{ inputs.PMD_VERSION }}:aggregate-pmd
        env:
          GITHUB_USER: ${{ secrets.SCM_USER }}
          GITHUB_TOKEN: ${{ secrets.SCM_TOKEN }}
          MAVEN_ARGS: ${{ inputs.MAVEN_ARGS }}
          MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }} 

      - name: PMD Annotation
        uses: jwgmeligmeyling/pmd-github-action@v1.2
        if: github.event_name == 'pull_request'
        with:
          path: "**/pmd.xml"

      - name: Upload PMD Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pmd-reports
          path: ${{ github.workspace }}/**/target/**/pmd.*
          retention-days: 30