name: "PMD & CPD SAST"

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'The Version of Java to use when compiling'
        default: '21'
        required: false
        type: string
      CHECKSTYLE_VERSION:
        description: 'The Version of Maven Checkstyle plugin to run for SAST'
        default: '3.6.0'
        required: false
        type: string
      MAVEN_ARGS:
        description: 'The Maven CLI options to use in the build command'
        default: --batch-mode --show-version --settings /tmp/java_maven_settings.xml
        required: false
        type: string
      MAVEN_OPTS:
        description: 'The build specific Maven CLI options to use in the build command'
        default: -Ddocker.skip=true -Dgpg.skip=true
        required: false
        type: string
    secrets:
      SCM_USER:
        required: true
      SCM_TOKEN:
        required: true

permissions:
  contents: read
  actions: read
  checks: write
  packages: read
  pull-requests: read

jobs:
  checkstyle-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.SCM_TOKEN }}
      
      - name: Set up JDK ${{ inputs.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          cache: "maven"
          distribution: "temurin"
          java-version: ${{ inputs.JAVA_VERSION }}

      - name: Retrieve Maven Settings File
        run: wget https://raw.githubusercontent.com/PallasSystems/infrastructure-ci/main/.github/workflows/java_maven_settings.xml -P /tmp/

      - name: Run Checkstyle
        run: mvn org.apache.maven.plugins:maven-checkstyle-plugin:${{ inputs.CHECKSTYLE_VERSION }}:checkstyle-aggregate
        env:
          GITHUB_USER: ${{ secrets.SCM_USER }}
          GITHUB_TOKEN: ${{ secrets.SCM_TOKEN }}
          MAVEN_ARGS: ${{ inputs.MAVEN_ARGS }}
          MAVEN_OPTS: ${{ inputs.MAVEN_OPTS }} 

      - name: Checkstyle Annotation
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        if: github.event_name == 'pull_request'
        with:
          path: "**/checkstyle-result.xml"

      - name: Upload Checkstyle Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-reports
          path: ${{ github.workspace }}/**/target/**/checkstyle*.*
          retention-days: 30