name: Build Verification of Node.JS docs project

on:
  workflow_call:
    secrets:
      SCM_USER:
        required: true
      SCM_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Node.JS 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Find yarn cache
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Pallas Scoped Github package repository
        run: echo "@pallassystems:registry=https://npm.pkg.github.com/" >> ~/.npmrc

      - name: Add authentication for scoped package repository
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.SCM_TOKEN }}" >> ~/.npmrc

      - name: Add normal registry
        run: echo "registry=https://registry.npmjs.org" >> ~/.npmrc

      - name: Run NPM Install on docs
        if: ${{ hashFiles('docs/') != '' }}
        run: npm ci
        working-directory: docs

      - name: Run NPM Build on docs
        if: ${{ hashFiles('docs/') != '' }}
        run: npm run build --if-present
        working-directory: docs  

      - name: Run NPM Test on docs
        if: ${{ hashFiles('docs/') != '' }}
        run: npm run test --if-present -- --coverage --passWithNoTests
        working-directory: docs

      - name: Test Report on docs
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: JEST Doc Tests # Name of the check run which will be created
          path: junit.xml # Path to test results
          reporter: jest-junit # Format of test results
        continue-on-error: true
        working-directory: docs

      - name: Save Code Linting Report JSON on docs
        run: npm run lint --if-present
        continue-on-error: true
        working-directory: docs

      - name: ESLint Annotate from Report JSON on docs
        uses: ataylorme/eslint-annotate-action@3.0.0
        with:
          report-json: 'eslint_report.json'
        continue-on-error: true
        working-directory: docs

      - name: Upload ESLint report on docs
        uses: actions/upload-artifact@v4
        with:
          name: eslint_docs_report.json
          path: eslint_report.json
        continue-on-error: true
        working-directory: docs

      - name: Upload StyleLint report on docs
        uses: actions/upload-artifact@v4
        with:
          name: stylelint_docs_report.json
          path: stylelint_report.json
        continue-on-error: true
        working-directory: docs
